{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   { "name": "pod", "label": "pod" }
  ]
 },
 "panels": [
  {
   "title": "Total Used Memory(已用总内存)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap(堆内存)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation(内存分配率/m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", pod=~\"$pod.*\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap(堆外内存)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{pod}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack(栈内存)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated(对象分配率,每分钟分配的对象个数)",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", pod=~\"$pod.*\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects(分配对象总数-释放对象总数=存活对象数量)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", pod=~\"$pod.*\"} - go_memstats_frees_total{namespace=\"$namespace\", pod=~\"$pod.*\"}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{namespace=\"$namespace\", pod=~\"$pod.*\"}[1m])"
    }
   ]
  }
 ]
}