{
 "title": "Kubernetes App JVM Overview",
 "description": "Dashboard for kubernetes JVM metrics with Prometheus",
 "tags": [
  "JVM",
  "prometheus",
  "app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(jvm_info, namespace)"
   },
   { "name": "app", "query": "label_values(jvm_info, job)" },
   { "name": "pod", "query": "label_values(jvm_info, pod)" }
  ]
 },
 "panels": [
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Threads current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "current [{{job}}]"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "daemon [{{job}}]"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "threads{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "threads [{$app}]"
    }
   ]
  },
  {
   "title": "JVM memory used by pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_pool_bytes_used{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}) by (pool)"
    }
   ]
  },
  {
   "title": "Threads Deadlocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "deadlock [{$app}]"
    }
   ]
  },
  {
   "title": "JVM memory committed by pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_pool_bytes_committed{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}) by (pool)"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "HTTP sessions active",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpsessions_active{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "sessions - {{$pod}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Process file descriptors gauge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "process_open_fs - {{$pod}}"
    },
    {
     "expr": "process_max_fds{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "process_max_fs  - {{$pod}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$Namespace\",job=~\"$app.*\",pod=~\"$pod.*\"}",
     "legendFormat": "loaded [{{pod}}]"
    }
   ]
  },
  {
   "title": "Garbage collection by gc",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_count{namespace=\"$Namespace\",job=~\"$app.*\", pod=~\"$pod.*\"}) by (gc)"
    }
   ]
  }
 ]
}